### ISSUE TITLE
More robust testing

### ISSUE THREAD

**Issue by jcrist** [blaze/rambling#107]
Several issues appeared after the merging of #101. It might be good to think about how to improve test coverage for this library. A few notes:

- Looking at the travis logs, sometimes errors appear but the test still passes (perhaps unintentionally): https://travis-ci.org/dask/knit/jobs/291657224.
- There are several possible code-paths that don't currently have tests (e.g. file names prefixed with `hdfs://`). It might be good to enumerate the possible cases and try to cover all/most of them.
- `test_hdfs_home` is always skipped as hdfs3 isn't installed on travis. Is this intentional?

Also might be good to document how a novice developer (myself :)) might get a test environment setup locally.

**Comment by martindurant** [comment]
I think I skipped the latter point when skimming this before - it is a point well made. This could go in the docs, but there's also the README in continuus_integration/. For myself, I use 

```
docker run -d -v /my/path/code:/code mdurant/hadoop
docker exec -it <hash-from-above> bash
```
