### ISSUE TITLE
Container ENV settings

### ISSUE THREAD

**Issue by quasiben** [blaze/rambling#11]
Allows users to set environment variables:

``` python
r. start_application(self, cmd, env = {'ENV_A': '/foo/bar', 'ENV_B': 2})
```

**Comment by mrocklin** [comment]
I would be satisfied with `start_application(self, cmd, env='dev')` where this would go and find my local conda installation, get the relevant environment directory, zip it up and send it along.  I'm not sure if this is doable though (see https://github.com/ContinuumIO/python-hadoop/issues/1).

If this worked then I could conceive of having multiple environments that I manage locally to deploy

``` python
r.start_application('dscheduler --port 9000', env='scheduler')
r.start_application('dworker 123.123.123.123:9000', env='worker', num_containers=10)
```

**Comment by quasiben** [comment]
Could be doable -- I should first resolve #4
