### ISSUE TITLE
CondaCreator on a different platform

### ISSUE THREAD

**Issue by superbobry** [blaze/rambling#116]
This might as well be a conda-specific question, but I'll give it a try anyway. Is there a way to use `CondaCreator` to assemble an environment for a platform other than the host? e.g. build a linux-64 environment on osx-64.

**Comment by martindurant** [comment]
There is no such option available in `knit`.
If you can figure out how to make conda do this (I don't know if it's possible), we can implement the option.

**Comment by quasiben** [comment]
I believe you can partially do this with [conda constructor](https://github.com/conda/constructor/).  I think you can build installers for OSX/Linux on Linux and similarly for OSX.  Windows, I think is a bit trickier.  @superbobry if you have time can you test and report back ?

**Comment by superbobry** [comment]
I've actually tested `constructor` and it does work for OSX/Linux combination. However, it makes certain assumptions about the environment, e.g. in my case I was missing `bunzip2` on the host OS, therefore I've rolled back to the `knit` approach.

> If you can figure out how to make conda do this (I don't know if it's possible), we can implement the option.

Well, that's the thing. I've failed to find a reasonable way to do it using conda as a black box. I think the trick implemented in `constructor` is to override the channels, but apparently, this is not possible for `conda env create`.

**Comment by jcrist** [comment]
Closing, as unrelated to knit. You may also be interested in https://conda.github.io/conda-pack/, a more generic tool for packaging conda environments. It also doesn't support packaging for a different platform, but doesn't rely on knit and more correctly handles prefixes and paths than the functionality in knit.
