### ISSUE TITLE
Container naming assumptions in ``yarn_api`` seem incorrect

### ISSUE THREAD

**Issue by superbobry** [blaze/rambling#119]
According to [`ContainerId`](https://hadoop.apache.org/docs/current/api/org/apache/hadoop/yarn/api/records/ContainerId.html#toString--) API docs, its string representation is constructed according to the following format:

> [...] `container_e*epoch*_*clusterTimestamp*_*appId*_*attemptId*_*containerId*` when epoch is larger than 0 (e.g. container_e17_1410901177871_0001_01_000005). *epoch* is increased when RM restarts or fails over. When epoch is 0, epoch is omitted (e.g. container_1410901177871_0001_01_000005).

https://github.com/dask/knit/blob/24a5e33ab5d6b4235cadf79f7e4244eb9935e9b4/knit/yarn_api.py#L130

It seems that the current version of the code ignores the fact that epoch can be non-zero and therefore could return an empty list of containers, even though there're running containers for a given application.

**Comment by martindurant** [comment]
Thank you @superbobry for your two issues. Would you be interested in submitting a PR to fix these, ideally with tests that show the fix?

**Comment by superbobry** [comment]
Surely, will do.

**Comment by jcrist** [comment]
Knit is being superseded by Skein (https://github.com/jcrist/skein). The new library is much more resilient to different hadoop configurations, and more flexible for deploying custom applications. If your intent is to deploy dask on yarn, dask-yarn (http://dask-yarn.readthedocs.io/) has been rewritten to use skein instead. Closing.
