### ISSUE TITLE
Support for constructing and env from an environment.yml 

### ISSUE THREAD

**Issue by superbobry** [blaze/rambling#121]
Do you think it could be useful to allow providing a single YAML file listing all dependencies instead of expecting them in `packages=[...]`? The same goes for channels, actually.

**Comment by martindurant** [comment]
This sounds reasonable. I don't know whether we would parse the YAML ourselves, or in this case call conda-env directly.

**Comment by mrocklin** [comment]
I believe that @jcrist's solution to this was to use conda to build an
environment normally (using any means normally avaiable to conda users),
then pack that into a redeployable environment using
https://github.com/jcrist/conda-pack , and then just send that file around.

**Comment by martindurant** [comment]
I believe if you are prepared to build the environment yourself as usual, then you can pass the resultant path to knit, and it will zip up the path for you.

**Comment by jcrist** [comment]
Closing, as the conda code in knit is deprecated. The recommendation is to use `conda-pack` and build the environment yourself beforehand with `conda` or `conda-env`.
