### ISSUE TITLE
No stdout

### ISSUE THREAD

**Issue by wrb2** [blaze/rambling#122]
Hi everyone,

I'm trying to run something using knit, like this:

```import knit
k = knit.Knit(autodetect=True, hdfs_home='/tmp/knit')
k.start('find .')
k.print_logs()
```

but I never get any output. The stdout log file is empty, as if the command didn't run anything.

Experimenting with ```touch``` I confirmed that the command gets ran on the datanode, but the output is lost.

Is this something to be expected? Or where should I look to be able to debug this?

Thank you

**Comment by martindurant** [comment]
Are you sure the directory that command runs in contains any files? I would try first with `echo`, and always look in both stdout and stderr. 

Note that logs either come directly from the node running the command while it is active, or from the log aggregation service *if* you have it enabled a few seconds after the command finishes. In this case, the "active" time of the command is essentially zero.

**Comment by wrb2** [comment]
Okay, so after some more investigation, I don't think the command gets ran at all.

Looking at logs:

```18/04/09 10:45:03 INFO knit.ApplicationMaster$: Launching container Container: [ContainerId: container_e22_1522846542906_1440_01_000002, NodeId: datanode-02.SNIP:45454, NodeHttpAddress: datanode-02.bdpdev.gin.merck.com:8042, Resource: <memory:3072, vCores:1>, Priority: 0, Token: Token { kind: ContainerToken, service: 54.40.237.190:45454 }, ]
18/04/09 10:45:03 INFO impl.NMClientAsyncImpl: Processing Event EventType: START_CONTAINER for Container container_e22_1522846542906_1440_01_000002
18/04/09 10:45:03 INFO impl.ContainerManagementProtocolProxy: Opening proxy : datanode-02.SNIP:45454
18/04/09 10:45:03 INFO knit.ApplicationMaster$: Container started container_e22_1522846542906_1440_01_000002
18/04/09 10:45:04 INFO knit.ApplicationMaster$: Container completed ContainerStatus: [ContainerId: container_e22_1522846542906_1440_01_000002, State: COMPLETE, Diagnostics: , ExitStatus: 0, ].getContainerId
```

Knit application master seems to run in `container_e22_1522846542906_1440_01_000001` and it says it runs `container_e22_1522846542906_1440_01_000002`. But there's no record of `container_e22_1522846542906_1440_01_000002` ever running at all - so that's actually the issue. I know I said that the command gets ran, but I think it was just me reusing test file names.

Any idea where to look?

**Comment by martindurant** [comment]
You should look in the resourcemanager and nodemanager logs to see what happened to container 000002.

**Comment by jcrist** [comment]
Knit is being superseded by Skein (https://github.com/jcrist/skein). The new library is much more resilient to different hadoop configurations, and more flexible for deploying custom applications. If your intent is to deploy dask on yarn, dask-yarn (http://dask-yarn.readthedocs.io/) has been rewritten to use skein instead. Closing.
