### ISSUE TITLE
No information on running tasks in Bokeh in EMR

### ISSUE THREAD

**Issue by j-bennet** [blaze/rambling#125]
When running an application with `DaskYARNCluster` in Amazon EMR, I can access the Bokeh UI, but there seems to be no information whatsoever on running tasks:

![screenshot 2018-04-14 18 14 43](https://user-images.githubusercontent.com/637013/38773965-2f3b1258-4010-11e8-9515-1acfa6a7f8d4.png)

I do see workers, so that's nice:

![screenshot 2018-04-14 18 17 51](https://user-images.githubusercontent.com/637013/38773971-53d426d6-4010-11e8-8a0c-a9cf6b0f380e.png)

But what is it with tasks? Am I missing something?

**Comment by martindurant** [comment]
Do tasks in fact run? Can you confirm that you don't have a previous scheduler process hanging around? 

In the cluster-runnig process, you can investigate what port the scheduler has actually used for bokeh, 

`cluster.local_cluster.scheduler.services['bokeh'].port`

or from the other script with the client

`client.scheduler_info()['services']['bokeh']`

**Comment by j-bennet** [comment]
They do run! I have to wrap it up for the day, but my application writes JSON to s3, and it finished running and wrote JSON. I'll check the bokeh address next time I run things.

**Comment by mrocklin** [comment]
I would be curious to know how you're setting up Dask on Amazon EMR.  FWIW
we tend to recommend Kubernetes and Helm these days for cloud deployments.
http://dask.pydata.org/en/latest/setup/cloud.html

**Comment by j-bennet** [comment]
Looks like this problem is not related to YARN scheduler. The same thing happens when running `dask-scheduler` and `dask-worker` processes from console on a EMR cluster. The scheduler output indicates bokeh UI on port 8787:

```
(dvss) [hadoop@ip-10-21-0-229 ~]$ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://10.21.0.229:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-ytyz4of_
distributed.scheduler - INFO - -----------------------------------------------
```

UI is accessible, I see workers etc., but no tasks.

**Comment by j-bennet** [comment]
Gah. User error! I failed to provide the running scheduler address to my code, and it quietly created a new `LocalCluster` as a fallback. So I was looking at the wrong UI. Smart me. Closing.

**Comment by mrocklin** [comment]
Thank you for reporting the issue and resolving it :)
