### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by jcrist** [blaze/rambling#133]
Skein (https://jcrist.github.io/skein/) is designed to be a Knit replacement, providing a more flexible and robust library for deploying applications on YARN.

Dask-Yarn (https://dask-yarn.readthedocs.io/en/latest/) has been rewritten to use Skein, and exists in its own separate repo.

At this point, I'd like to deprecate knit, and add a note to the readme and repo. Thoughts @martindurant, @quasiben?

**Comment by martindurant** [comment]
100% agree

The only things of interest that exist here but not in skein are about directly fetching logs, cluster and app/container details. That stuff maybe worth salvaging or providing via the skein client (prefer the latter because of the uncertainty of accessing the HTTP endpoint).

**Comment by jcrist** [comment]
Most of that (except the logs) is currently available via skein. I'm not sure if I want to wrap reading logs yet - the spark and hadoop documentation all mentions `yarn logs -applicationId ...` as the way to access logs (there's no easy generic way to do this with the hadoop libraries), and users seem fairly familiar with that. If needed issues for more features can be filed over there.

I'll push a commit deprecating things then.

**Comment by jcrist** [comment]
Done.

**Comment by martindurant** [comment]
I do recommend trying to make all the functionality available in code (eventually) - having to drop to the shell or going to the various monitoring pages is annoying and a break in the workflow.
