### ISSUE TITLE
Rename rambling

### ISSUE THREAD

**Issue by koverholt** [blaze/rambling#14]
`rambling` provides (or will provide):
- Distributed shell functionality
- Log fetching for remote YARN jobs
- Resource allocation of containers (e.g., CPU, memory)
- Deploy conda environments via YARN job submission
- Container restart/dynamic allocation

Names of other YARN-related projects:
- py-yarn
- yarn-api-client
- Llama
- Kitten
- Apache Twill
- Apache Slider

**Comment by mrocklin** [comment]
Knit

**Comment by quasiben** [comment]
Ah, thanks for starting this @koverholt. Other suggestions i've seen:
- pyalloc
- pyarn
- pyrn
- yarnsnake

**Comment by quasiben** [comment]
I'm +1 on `knit`.  I don't see an apache yarn related projects named that.

**Comment by koverholt** [comment]
I am also +1 on `knit`
- fiber
- stingray
- [sanshin](https://en.wikipedia.org/wiki/Sanshin)
- yarpy
- yarnly
- silkworm
- microfiber
- fray
- trunksnake

**Comment by quasiben** [comment]
I also like sanshin.  Maybe we save that for the umbrella project ramlbing, distrbuted, hdfs3?

**Comment by izaid** [comment]
weave

**Comment by quasiben** [comment]
Unfortunately, `weave` is/was already an Apache YARN project:
https://github.com/continuuity/weave

It has since been renamed **Twill**

**Comment by teoliphant** [comment]
+1 knit

**Comment by seibert** [comment]
+1 knit, and it opens up the opportunity for sweater puns

**Comment by koverholt** [comment]
Looks like `knit` is the clear winner here, thanks for the feedback, everyone!

**Comment by koverholt** [comment]
Renaming complete, thanks Ben!
