### ISSUE TITLE
Requirements For Build

### ISSUE THREAD

**Issue by quasiben** [blaze/rambling#20]
Users may not need the full jdk installed but it does resolve build issues like the following:

```
[ERROR] Failed to execute goal on project knit: Could not resolve dependencies for project io.continuum:knit:jar:1.0-SNAPSHOT: Could not find
 artifact jdk.tools:jdk.tools:jar:1.7 at specified path /usr/lib/jvm/java-7-openjdk-amd64/jre/../lib/tools.jar ->
```

On Ubuntu:

```
aptitude install openjdk-7-jdk
```

Would be good to find the minimum amount of packages: `openjdk-7-jre-lib` and `ant` and something else?

**Comment by martindurant** [comment]
Will be solved with conda recipe
