### ISSUE TITLE
Resource Respect

### ISSUE THREAD

**Issue by quasiben** [blaze/rambling#3]
Launching a python process in a yarn container can effectively breakout of the requirements set by AMRM.  Python processess should properly respect cores, mempry, etc. constraints

**Comment by mrocklin** [comment]
It may not be possible for Yarn to enforce these in the general case.  However it might be useful to be able to claim these sorts of contraints in cases where the run program can enforce them itself.

You can always track the memory/CPU usage of a process with `psutil.Process(pid).get_*`

**Comment by martindurant** [comment]
dask workers will now tend to kill themselves. Since they are the main use case we envision for Knit, I am closing this. I do not intend to put a process-watcher into every container in the near-mid future.
