### ISSUE TITLE
Dask-yarn command line interface

### ISSUE THREAD

**Issue by mrocklin** [blaze/rambling#55]
I would like to have access to a dask-yarn CLI

```
$ dask-yarn --nworkers 10 --threads-per-worker 4 --env "python=3 numpy pandas dask distributed"
```

Where is the right place for this command line interface to exist?  The dask/distributed repository?  dask/knit (here)?  dask/dask-yarn (a new project)?

**Comment by martindurant** [comment]
I think it would be best to merge dask-yarn into here, and have a CLI for it here (similar to dask-kubernetes, with luck).

**Comment by martindurant** [comment]
cc @jcrist

**Comment by jcrist** [comment]
dask-yarn has moved to https://github.com/dask/dask-yarn. Closing.
