### ISSUE TITLE
create conda-forge recipe

### ISSUE THREAD

**Issue by quasiben** [blaze/rambling#65]
@martindurant

**Comment by martindurant** [comment]
I gather this is intended to work with linux and osx? The *target* must always be linux, though, right? In that case, does knit-conda produce a viable bundle?

**Comment by quasiben** [comment]
Occasionally, I test locally with OSX where I am also using YARN on OSX.   But I think what you are asking is, "does knit on OSX target Linux?"  If that is the question, the answer is, no.
