### ISSUE TITLE
container cannot start dask workers

### ISSUE THREAD

**Issue by zwang1986** [blaze/rambling#69]
This post refers to my last issue. [task submitted never be executed using dask-yarn](https://github.com/dask/distributed/issues/1285)
New findings: 
1. Yarn save application logs after killing my dask application;
2. From Yarn log, it can be found that wokers are not started in container.

**Comment by jcrist** [comment]
dask-yarn has been rewritten, and should be more robust to different hadoop configurations. Please see the docs (https://dask-yarn.readthedocs.io/en/latest/) and new repo (https://github.com/dask/dask-yarn). Closing.
