### ISSUE TITLE
Knit on YARN... error with continuous integration readme ?

### ISSUE THREAD

**Issue by jpoullet2000** [blaze/rambling#74]
Following the continuous integration [README](https://github.com/dask/knit/blob/master/continuous_integration/README.md) 

Everything went fine until I try to test knit on YARN... below the error I get

```
bash-4.1# hadoop jar /knit/knit_jvm/target/knit-1.0-SNAPSHOT.jar io.continuum.knit.Client hdfs://localhost:9000/jars/knit-1.0-SNAPSHOT.jar 1 "python -c 'import sys; print(sys.path); import random; print>
Error: Unknown argument 'hdfs://localhost:9000/jars/knit-1.0-SNAPSHOT.jar'
Error: Unknown argument '1'
Error: Unknown argument 'python -c 'import sys; print(sys.path); import random; print(str(random.random()))''
```

**Comment by martindurant** [comment]
This README will be rewritten within the next few days, please watch this space. Is it important to you to be able to run a command like this from the shell, or are you happy to run from a python session? The latter is far higher priority in my personal reckoning.
