### ISSUE TITLE
add timeouts to requests calls

### ISSUE THREAD

**Issue by martindurant** [blaze/rambling#85]
Network setups can sometimes leave requests.get and such to hang indefinitely. There should always be timeouts; and methods like kill() should decide what to do in the case that, for example, the application status is not available because of the timeout.

**Comment by jcrist** [comment]
Can the application status be retrieved in a way that uses the client instead of the requests api? On my system all api requests currently hang (not sure why, probably some security thing), so the ability to use alternative channels would be nice.

**Comment by martindurant** [comment]
Yes, the status can in theory be retrieved from the client over RPCs, and it was coded this way in the past, and comes with other problems in the python-java gateway. I wanted a simpler way to do it, and not to be forced to keep the client process around. 
It probably is also possible to fetch the status directly from the application-master, but that would obviously fail if the master ends. Having both possibilities sounds like a pain! :|
In the long run, recoding the client to use thrift RPCs from python directly may be an answer, but that would take some careful thinking about, since it would need to replicate all the hidden magic buried within yarn code.
