### ISSUE TITLE
kerberos on rest endpoints

### ISSUE THREAD

**Issue by martindurant** [blaze/rambling#86]
It is possible to secure http rest endpoints with kerberos. We could talk with these either by:
- depend on [requests-kerberos](https://github.com/requests/requests-kerberos) to do the right thing
- grab a token from our client, which talks RPC (note that this might be easy to implement, but hurts our chances to implement more calls on http instead of relying on the client). Probably a hdfs token would do too...

**Comment by martindurant** [comment]
+ auto-detect use of Knox hadoop proxy: look in core-site.xml to see if Knox is about, and infer appropriate URL endpoint from gateway-site.xml if required.

cc @jcrist

**Comment by jcrist** [comment]
We have knox installed and running on our edge node. Currently this prevents any of the `yarn-api` from working, as all requests time out. I was able to fix this by:

- Removing all local `http_proxy`/`https_proxy`/... settings I had in my `.bash_profile`. These were interfering with the subsequent steps (there may be a way around removing them, not sure)
- Looking up the knox port in `gateway-site.xml`
- Switching the yarn https url to `https://localhost:KNOXPORT/gateway/default/resourcemanager/v1`
- Creating an instance of `requests.auth.HTTPBasicAuth` with my username/password, and passing it to every requests call
- Passing `verify=False` to every ssl call. I suspect this may be an issue with how our system is configured, but perhaps this is common.

Doing all of the above I can successfully make yarnapi calls using knit.

Note that the java client works fine without any of this, as does the yarn cli, so somehow they're able to make due without getting my password or being confused by proxy environment variables.

**Comment by martindurant** [comment]
So action items:

- document that a YARN cluster may be on Knox or other proxy, with requests timeouts as the symptom, and that you will need to ask an administrator for the correct URL prefix that should call
- provide config options to pass user/pass into requests headers
- provide config options or infer from core-site, to whether http access is kerberos protected, in which case enable requests-kerberos (like curl negotiate).

Note that the yarn client doesn't suffer from these problems because it simply doesn't implement various ways to gather information. How the CLI can gets logs from running containers, which requires an HTTP call to a worker node, I don't know (maybe it can't).
