### ISSUE TITLE
language settings for containers

### ISSUE THREAD

**Issue by martindurant** [blaze/rambling#87]
Click sometimes is not OK with C.UTF-8; anecdotally, en_US.utf-8 can work where the formal doesn't. Should make this a configuration parameter and try to make the default be based on the setting in the host environment.

**Comment by jerry-dumblauskas** [comment]
+1

**Comment by martindurant** [comment]
Needs some work, as it turns out that standard languages are not available in docker containers (the testing platform), and presumably other situations, so need a thorough backup.
